DATASET:
  BATCH_SIZE: 8
  CROP_FACTOR: 0.5
  CROP_PROB: 0.2
  DATASETS_AND_RATIOS: 'static-hdri-bmi'
  IMG_RES: 224
  MESH_COLOR: pinkish
  NOISE_FACTOR: 0.4
  NUM_WORKERS: 0
  PIN_MEMORY: true
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  VAL_DS: static-hdri-bmi
  CROP_PERCENT: 1.0
  ALB: true
  PARTS_COUNT: 200
  PART_IDX: 2
EXP_NAME: bedlam_cam_ready
LOG_DIR: logs
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
MODEL:
  BACKBONE: hrnet_w48-conv
  BETA_LOSS_WEIGHT: 0.01
  JOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 10.0
TESTING:
  WP_VIS: true
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 50
  MAX_EPOCHS: 200
  PRETRAINED_CKPT: coco
  PRETRAINED_LIT: null
  RELOAD_DATALOADERS_EVERY_EPOCH: false
  RESUME: null
  TEST_BEFORE_TRAINING: false
  LOG_EVERY_N_STEPS: 1
  WP_VIS: false
  CKPT_PREF: 'high_bmi_{epoch}'
  CKPT_POSTFIX: 'high_bmi'
TRIAL:
  criterion: mse
